name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
          
    - name: Running Horusec Security (SAST)
      run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p .
    
    - name: Build Docker
      run: |
          DOCKER_BUILDKIT=1 docker build -t petclinic .
          
#    - name: Run Container
#      run: |  
#          docker run --rm -p 8080:8080 --name petclinic petclinic

#    - name: ZAP Scan
#      uses: zaproxy/action-full-scan@v0.3.0
#      with:
#        target: 'https://dvwa.co.uk/'
#testing
